[window]
padding = { x = 5, y = 5 }

[font]
normal = { family = "kirsch2x", style = "Medium" }
size = 15

[colors.primary]
foreground = "#2aed8b"     #"#dbf8fc"
background = "#380510"

[colors.cursor]
text = "#2aed8b"
cursor = "#2ad6ed"

[colors.normal]
black = "#160106"
red = "#f21f23"
green = "#3cbf0d"
yellow = "#ebf21f"
blue = "#457df7"
magenta = "#f4338d"
cyan = "#45dbef"
white = "#dbf8fc"
